### PR TITLE
Added a bunch of new features

### PR DESCRIPTION
**Pull request by kvfs2k07**
- Made AimBot read-only
- Added Deathmatch Mode
- Splitted head and joints (esp)
- Added random delay to triggerbot
- Fixed fov and player lock (sometimes it was acting weird)

### CODE REVIEW

**Comment by kvfs2k07** [comment]
ongoing issue: aimbot stop working when leaving game and joining another game

**Comment by goldykrishna** [comment]
> ongoing issue: aimbot stop working when leaving game and joining another game

@Skwrr : same issue after match ,joining new game ,aimbot stopped working.
can u pls make section for saving settings ,so that everytime we need not to change

scrnli_6_13_2024_5-44-08 PM
and still there is write functions ,is it for recoil ?

**Comment by kvfs2k07** [comment]
Features like rcs, fov change and anti flash have to write memory into the game, so I can't make it only read from memory and make it not to flash you.

About the config, yea sure, I'm working on it. Shouldn't be very hard

**Comment by goldykrishna** [comment]
> Features like rcs, fov change and anti flash have to write memory into the game, so I can't make it only read from memory and make it not to flash you.
> 
> About the config, yea sure, I'm working on it. Shouldn't be very hard

Aimbot stopped working after joining another match. 
Can u pls temporary remove all writeable memory features, and try to add config options soon as u said.

**Comment by goldykrishna** [comment]
@Skwrr

**Comment by kvfs2k07** [comment]
The aimbot issue should be fixed, I already tested it and works perfectly.

I won't be removing any write feature because I'd have to remove 40% of the code, which may break other features and/or some checks in the main loop. You can clone the repo and remove the write features yourself.

Config file is almost done, I'm testing everything and seems like I'll be commiting a push in the next hour

**Comment by goldykrishna** [comment]
. @Skwrr okay thanks for that. Waiting for update.

**Comment by kvfs2k07** [comment]
Configuration file settings has been commited.
I also added a feature so you don't need to have cs2 open for the cheat to work. It will now wait for the process and do stuff when cs2 is open an loaded

**Comment by goldykrishna** [comment]
@Skwrr i checked the update , it is working pretty well, config n all. i would inform u for bugs ,havent  checked in online matches yet.

but i want to confirm from you few things as far i observed in coding:
1. ESP
2. Aimbot
3. trigger bot
All three are read only , no writeable functions there , pls confirm once more .

**Comment by goldykrishna** [comment]
@Skwrr all working great , but there is very much inconsistency in aim bot with player lock+team check.
kindly check that ..........

**Comment by kvfs2k07** [comment]
> @Skwrr i checked the update , it is working pretty well, config n all. i would inform u for bugs ,havent checked in online matches yet.
> 
> but i want to confirm from you few things as far i observed in coding:
> 
> 1. ESP
> 2. Aimbot
> 3. trigger bot
>    All three are read only , no writeable functions there , pls confirm once more .

yes, those 3 features are completely read only.

**Comment by kvfs2k07** [comment]
> @Skwrr all working great , but there is very much inconsistency in aim bot with player lock+team check. kindly check that ..........

I haven't played deathmatch with the aimbot update yet, I'll be working on it.

**Comment by kvfs2k07** [comment]
It seems like is working fine, only issue I found (in every game mode) is when there are more than 1 person inside the FOV, the cheat will choose the first in the entity list (which might be the worst enemy to choose in that situation).
I'll be adding a checkbox to the "Miscelanous aimbot features" tab to whether choose the closest player to crosshair, the closest player to the local player or choose random player inside the FOV circle.

**Comment by goldykrishna** [comment]
i checked the latest menu , havent checked rcs yet in game but there is no misc aimbot features tab as u mentioned .
latest canva

**Comment by goldykrishna** [comment]
@Skwrr will check aimbot in competitive matches n will give u review..

**Comment by goldykrishna** [comment]
@Skwrr i checked RCS ( read only) it isnt working well for me , will try aimbot in online matches and inform u....

**Comment by kvfs2k07** [comment]
> i checked the latest menu , havent checked rcs yet in game but there is no misc aimbot features tab as u mentioned . latest canva

Inside "Aim" tab, there is a another tab on the top right corner

**Comment by kvfs2k07** [comment]
> @Skwrr i checked RCS ( read only) it isnt working well for me , will try aimbot in online matches and inform u....

Have you set "Aim sensivity" to your mouse sensivity in game?
image

**Comment by goldykrishna** [comment]
@Skwrr  Yes, after adjusting mouse sensitivity it's working well RCS, great work ✌. 

Aim bot + player lock + team check = still inconsistent. 
But if I remove team check it's working well.

**Comment by kvfs2k07** [comment]
Can you send a video which you show the behavior of aimbot + player lock + team check?

**Comment by goldykrishna** [comment]
Okay I will test it more in online matches and will provide info...

**Comment by goldykrishna** [comment]
update latestd
@Skwrr there is no Miscellaneous aimbot features" tab as u mentioned.

**Comment by kvfs2k07** [comment]
> update latestd @Skwrr there is no Miscellaneous aimbot features" tab as u mentioned.

My bad, I meant "Miscellaneous aim functions"

**Comment by kvfs2k07** [comment]
Aimbot target preference added.
Maybe might help with the inconsistence of  aimbot + player lock + team check

**Comment by goldykrishna** [comment]
@Skwrr i will test it and inform u....

**Comment by goldykrishna** [comment]
@Skwrr can u add c4 esp... Is it possible?

**Comment by kvfs2k07** [comment]
Sure, I Will make It on the next update

**Comment by goldykrishna** [comment]
c4esp
@Skwrr  c4 esp only being displayed after planting , it should be throughout the match of opponent ,so that easy to find c4 carrier.
and still now testing aim bot +player check +lock ,will check on online matches.
kindly fix the c4 esp issue

**Comment by goldykrishna** [comment]
@Skwrr till now aimbot is inconsistent in death matches online checked different target preferences ( aimbot + rcs + player lock + team check) 

Combination  2 = ( aimbot + rcs + player lock) without team check is also inconsistent in this version,

**Was consistent when u made rcs read only version before releasing exe**, so i m using that, it's best if we do team check off .

**Comment by goldykrishna** [comment]
@Skwrr Update :
Working Combination 1 = ( aimbot + rcs + no prefered target/ choose farthest)

 Working Combination 2 = ( aimbot + rcs + team check + no prefered target/ choose farthest)

**In this version player lock isn't working at all...**

**Comment by kvfs2k07** [comment]
Will add an option for C4 Carrier in next version.

In previous versions, player lock weren't working properly, i forgot a check in aim.cpp

Aimbot is not designed to work among rcs, so I'll be trying to add anything to make aimbot work among rcs

**Comment by goldykrishna** [comment]
@Skwrr  ok waiting for update

**Comment by imwqqz** [comment]
I need to add smt the recoil control is seems too obvious that ur cheating.

**Comment by goldykrishna** [comment]
@Skwrr any update?

**Comment by kvfs2k07** [comment]
> @Skwrr any update? 

I'm halfway done, I fixed player lock and preferred target. 

I'm having some trouble making RCS work with aimbot.

**Comment by kvfs2k07** [comment]
> I need to add smt the recoil control is seems too obvious that ur cheating.

I could add a "Smooting" option to make it less obvious or a feature that paid cheats has which show you the pattern your recoil will be controlled based off x and y offset

**Comment by goldykrishna** [comment]
> > @Skwrr any update?
> 
> I'm halfway done, I fixed player lock and preferred target.
> 
> I'm having some trouble making RCS work with aimbot.

Okay

**Comment by imwqqz** [comment]
> > I need to add smt the recoil control is seems too obvious that ur cheating.
> 
> I could add a "Smooting" option to make it less obvious or a feature that paid cheats has which show you the pattern your recoil will be controlled based off x and y offset

I need you to update ur last merge if u had changed smt i think if i got time ill fix the recoil control cuz sometimes the recoil control gets bugged and move ur mouse to the sky.

**Comment by kvfs2k07** [comment]
> > > I need to add smt the recoil control is seems too obvious that ur cheating.
> > 
> > 
> > I could add a "Smooting" option to make it less obvious or a feature that paid cheats has which show you the pattern your recoil will be controlled based off x and y offset
> 
> I need you to update ur last merge if u had changed smt i think if i got time ill fix the recoil control cuz sometimes the recoil control gets bugged and move ur mouse to the sky.

i forgot to push the changes, sorry haha

**Comment by imwqqz** [comment]
U know how does obs/discord sharing bypass word i think it will be a very good feature

**Comment by kvfs2k07** [comment]
~~I'd have to do handle hijack and I've never done it before~~

~~And I think Dear ImGUI is kinda good, isn't it?~~

I missunderstood, it's already obs and discord sharing proof

Edit:
If you capture only cs2.exe with OBS, it won't be able to capture the visuals. Same as discord sharing.
To make the visuals visible for OBS and Discord Sharing, you have to capture the whole screen.

**Comment by imwqqz** [comment]
> ~I'd have to do handle hijack and I've never done it before~
> 
> ~And I think Dear ImGUI is kinda good, isn't it?~
> 
> I missunderstood, it's already obs and discord sharing proof

Oh, ok then. Btw about the ImGui i think we could update it to the lastest if isnt.

**Comment by kvfs2k07** [comment]
It's not updated to the latest, and I think there's no need to update ImGUI

**Comment by goldykrishna** [comment]
@Skwrr , I tested latest one. 
Aimbot + rcs + player lock working fine without player check. 

With player check we have to remove either rcs Or player lock / remove both to get work. 

And waiting for c4 esp carrier  update.

**Comment by imwqqz** [comment]
> @Skwrr , I tested latest one. 
> Aimbot + rcs + player lock working fine without player check. 
> 
> With player check we have to remove either rcs Or player lock / remove both to get work. 
> 
> And waiting for c4 esp carrier  update. 

Could add timer to bomb.

**Comment by kvfs2k07** [comment]
> > @Skwrr , I tested latest one.
> > Aimbot + rcs + player lock working fine without player check.
> > With player check we have to remove either rcs Or player lock / remove both to get work.
> > And waiting for c4 esp carrier  update.
> 
> Could add timer to bomb.

yeah, but I wanna make it in a different way than other cheats

**Comment by kvfs2k07** [comment]
> @Skwrr , I tested latest one. Aimbot + rcs + player lock working fine without player check.
> 
> With player check we have to remove either rcs Or player lock / remove both to get work.
> 
> And waiting for c4 esp carrier update.

does rcs + aimbot work fine?

**Comment by goldykrishna** [comment]
@Skwrr as I said earlier it's working only without team check, with team check isn't working at all. 

Without team check = aimbot + RCS + player lock

With team check not working.

**Comment by imwqqz** [comment]
@Skwrr you're going to add lorr new feautres like nospread or rapidfire?

**Comment by kvfs2k07** [comment]
> @Skwrr you're going to add lorr new feautres like nospread or rapidfire?

short answer: no

those freatures are hard asf in an external cheat, I've already tried making AutoWall for triggerbot but I didn't understand anything I was doing + it wasn't working. I gave up on doing features like NoSpread, RapidFire, AutoWall, SilentAim, AntiAim, etc.

**Comment by imwqqz** [comment]
tim_apple not working in the new update. anyone confirm?

**Comment by kvfs2k07** [comment]
Update offsets

**Comment by goldykrishna** [comment]
@wqq-z working fine.....update offsets

**Comment by imwqqz** [comment]
> @wqq-z working fine.....update offsets

True, i though that the updateoffsets it self updates it automatically

**Comment by 1nteg3r** [comment]
has anyone figured out how to fix the bone esp being all messed up at times? sometimes rendering bones that arent there, or even getting lines on the middle of my screen?

**Comment by imwqqz** [comment]
> has anyone figured out how to fix the bone esp being all messed up at times? sometimes rendering bones that arent there, or even getting lines on the middle of my screen?

I didnt see rhe code but there should be 2 possibility of causing this problem when the code get the pos of the players or is the rendering issue

**Comment by kvfs2k07** [comment]
I think it's an issue related with the Game memory. 
I tried debugging where bones where at and where player origin was located, When the bones glitched out the player origin was still showing the player's real position but the bones are stuck in the same position for 5 - 10 seconds. 

You can also see this in game if you hardcode the player's head position in the box esp. The box will be moving but the skeleton will be stuck in place.

**Comment by kristofhracza** [comment]
> I think it's an issue related with the Game memory. I tried debugging where bones where at and where player origin was located, When the bones glitched out the player origin was still showing the player's real position but the bones are stuck in the same position for 5 - 10 seconds.
> 
> You can also see this in game if you hardcode the player's head position in the box esp. The box will be moving but the skeleton will be stuck in place.

This is a bug in the game, not the cheat.
It’s been discussed on UC as well.

**Comment by kvfs2k07** [comment]
@kristofhracza do you also got this issue where esp and aimbot stop working but everything else does?
I don't know how to fix it and I think it's also a game issue.

**Comment by LauraSavall** [comment]
@Skwrr 
RCS don't seem to work or maybe I'm missing a parameter ... like dont aimbot + RCS ?

**Comment by LauraSavall** [comment]
> @Skwrr as I said earlier it's working only without team check, with team check isn't working at all.
> 
> Without team check = aimbot + RCS + player lock
> 
> With team check not working.

I just read it...

**Comment by kvfs2k07** [comment]
> > @Skwrr as I said earlier it's working only without team check, with team check isn't working at all.
> > Without team check = aimbot + RCS + player lock
> > With team check not working.
> 
> I just read it...

that seems to be fixed after v11
(not working for me but it somehow does for @goldykrishna )

**Comment by goldykrishna** [comment]
@Skwrr any update of c4 carrier esp?

**Comment by kvfs2k07** [comment]
> @Skwrr any update of c4 carrier esp? 

Couldn't find any offset for the C4 Carrier, Google didn't help either.

**Comment by goldykrishna** [comment]
@Skwrr glow c4 as u are you are glowing weapon...

**Comment by goldykrishna** [comment]
@Skwrr is it possible to add spectator?

**Comment by LauraSavall** [comment]
> @Skwrr is it possible to add spectator?

You mean, if someone is on your POV ?

https://github.com/RatPoison-dev/RatPoison/blob/master/src/main/kotlin/rat/poison/scripts/SpectatorList.kt

**Comment by goldykrishna** [comment]
@LauraSavall yes

**Comment by kvfs2k07** [comment]
First version of spectator list has been pushed, I'll be adding color customization, customizable text size and maybe a position editor.

**Comment by goldykrishna** [comment]
> First version of spectator list has been pushed, I'll be adding color customization, customizable text size and maybe a position editor.

Position editor means?

**Comment by kristofhracza** [comment]
I will make this repo a public archive in a few days! 

If you want all your code saved, please do it now.

**Comment by LauraSavall** [comment]
Do you think it's possible to add this kind of Script ;
https://github.com/RatPoison-dev/RatPoison/blob/master/src/main/kotlin/rat/poison/scripts/BombTimer.kt
😁

**Comment by kvfs2k07** [comment]
> I will make this repo a public archive in a few days!
> 
> If you want all your code saved, please do it now.

wait, are you archiving this?

**Comment by kvfs2k07** [comment]
> > First version of spectator list has been pushed, I'll be adding color customization, customizable text size and maybe a position editor.
> 
> Position editor means?

move the spectator list wherever you want in the screen

**Comment by kvfs2k07** [comment]
> > I will make this repo a public archive in a few days!
> > If you want all your code saved, please do it now.
> 
> wait, are you archiving this?

I cloned my repo and somehow you're as a contributor in it lmao.
I won't be removing you as I'd like to give you some credit for using your source code.

**Comment by kvfs2k07** [comment]
Pull request cloned and moved to https://github.com/Skwrr/Dexterion

**Pull request closed without merging**
